export const projects = [
  {
    title: 'Inventory Management (Vue)',
    description: "A website for handling all inventory management functionalities and business logic required to handle the product inventory of a business.",
      image: 'https://i.ibb.co/S633RgP/Vue-Inventory-Management-Home.png',
      tags: ['Vue', 'Tailwind CSS', 'ChartJs', 'Node'],
    source: 'https://github.com/Muhtasim-Fuad-Showmik/Vue-Inventory',
    visit: 'https://github.com/Muhtasim-Fuad-Showmik/Vue-Inventory',
    id: 0,
    deployed: false,
  },
  {
    title: 'Inventory Management (Qwik)',
    description: "A website for handling all inventory management functionalities and business logic required to handle the product inventory of a business.",
      image: 'https://i.ibb.co/6H60DXV/Qwik-Inventory-Home.png',
      tags: ['Qwik', 'Vanilla CSS', 'ChartJs', 'Node'],
    source: 'https://github.com/Muhtasim-Fuad-Showmik/Qwik-Inventory',
    visit: 'https://github.com/Muhtasim-Fuad-Showmik/Qwik-Inventory',
    id: 1,
    deployed: false,
  },
  {
    title: 'ReactBlog',
    description: "A blog site with social media functionalities created using React, Material UI, Boxicons, and a Django backend.",
      image: 'https://i.ibb.co/bHr39FK/React-Blog-Home.png',
      tags: ['React', 'Material UI', 'Django', 'Node'],
    source: 'https://github.com/AbrarZahin247/ReactBlog',
    visit: 'https://github.com/AbrarZahin247/ReactBlog',
    id: 2,
    deployed: false,
  },
  {
    title: 'BodyWrap',
    description: "An ecommerce website that is tailored towards selling apparel items online. The project is made using Mongoose, Express, React and Node JS. It has security implementations using AES hashing and also has an admin dashboard prepared for the business owner.",
      image: 'https://i.ibb.co/GPn2NC2/bodywrap.png',
      tags: ['Mongo', 'Express', 'React', 'Node'],
    source: 'https://github.com/Muhtasim-Fuad-Showmik/BodyWrap',
    visit: 'https://github.com/Muhtasim-Fuad-Showmik/BodyWrap',
    id: 3,
    deployed: false,
  },
  {
    title: 'Tent',
    description:"A website that allows users to search for new campgrounds to visit, review campgrounds existing on the system, as well as add new campgrounds to the system. The system is built using Mongoose, Express and Node JS and has several security implementations and map implementations on it. For a sample credential to use for the site you may use the username of \"Guest\" and the password \"guestpass\".",
    image: 'https://i.ibb.co/xj0p7XS/tent.png',
    tags: ['Mongo', 'Express', 'Node'],
    source: 'https://github.com/Muhtasim-Fuad-Showmik/Tent',
    visit: 'http://powerful-river-65642.herokuapp.com/',
    id: 4,
    deployed: true,
  },
  {
    title: 'Corgitto',
    description: "A website for adopting Corgi dogs experimenting with Qwik on the frontend and local storage of browsers to handle the backend logic.",
      image: 'https://i.ibb.co/b3RD0MN/Corgitto-Home.png',
      tags: ['Qwik', 'Tailwind CSS', 'Local Storage', 'Node'],
    source: 'https://github.com/Muhtasim-Fuad-Showmik/CorgiStore',
    visit: 'https://github.com/Muhtasim-Fuad-Showmik/CorgiStore',
    id: 5,
    deployed: false,
  },
  {
    title: 'Rain Caller',
    description: "A website for fetching weather data from 'Open Weather API' to show data of saved location, while allowing users to save new locations for later access as well. The backend logic for this application was handled using Axios and Local Storage of browsers as a data storage.",
      image: 'https://i.ibb.co/f8YbZG6/Rain-Caller-Home.png',
      tags: ['Vue', 'Tailwind CSS', 'Node'],
    source: 'https://github.com/Muhtasim-Fuad-Showmik/VueWeatherApp',
    visit: 'https://github.com/Muhtasim-Fuad-Showmik/VueWeatherApp',
    id: 6,
    deployed: false,
  },
  {
    title: 'Order Management',
    description:"A sample application with three versions implemented inside, where the combination of SAP UI5 frontend, Vue frontend, and SAP CAP backend is tested out using the same logic on all projects.",
    image: 'https://i.ibb.co/42Wh7dp/Order-Management-Home.png',
    tags: ['SAP UI5', 'Vue', 'i18n', 'SAP CAP'],
    source: 'https://github.com/Muhtasim-Fuad-Showmik/UI5-OrderManagement',
    visit: 'https://github.com/Muhtasim-Fuad-Showmik/UI5-OrderManagement',
    id: 7,
    deployed: false,
  },
  {
    title: 'Customer Overview (Cloud DNA)',
    description:"A sample SAP implementing Cloud DNA training logics using SAP UI5 and SAP CAP, with updated OData v4 logic instead of the training's usual OData v2 logic.",
    image: 'https://i.ibb.co/d7t1PkF/Cloud-DNACustomer-Overview-Home.png',
    tags: ['SAP UI5', 'SAP CAP'],
    source: 'https://github.com/Muhtasim-Fuad-Showmik/CloudDNA-Training',
    visit: 'https://github.com/Muhtasim-Fuad-Showmik/CloudDNA-Training',
    id: 8,
    deployed: false,
  }
];

export const TimeLineData = [
  { year: 2016, text: 'Began pursuing my BSCSE degree', },
  { year: 2020, text: 'Acquired my BSCSE degree with 3.98 CGPA and got employed as a Research Consultant (Junior Programmer) at CEGIS', },
  { year: 2021, text: 'Acquired a certificate on completion of a Web Development Bootcamp on Udemy', },
  { year: 2022, text: 'Began working as a Senior Developer at SCT Bangla (a sister concern of Schertech)', },
];